# site settings
title: Perez Productions
subtitle: 
email: noah@perez.productions
description: I provide video production services in Gainesville, Florida.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://perez.productions # the base hostname & protocol for your site
author: Noah Perez

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://instagram.com/_the_noah_perez_/
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

logo: assets/images/logo.png

#seo tag
social:
  name: Noah Perez
  links:
    - https://instagram.com/_the_noah_perez_/
    - https://www.youtube.com/@Perez_Productions

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
- jekyll-seo-tag

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
